on:
  push:
    branches:
      - "feature/*"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Merge branch
        uses: Germanedge/github-auto-branch-merge@main
        with:
          target_branch: 'dev'
          source_branch: ${{ env.GITHUB_REF_NAME }}
          commit_message: "[Automated] Merge branch '${{env.GITHUB_REF_NAME}}' into {target_branch}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
